# Generated by Django 4.1.7 on 2023-04-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettingsDB',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('int', models.IntegerField(default=0)),
                ('str', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
