# Generated by Django 4.1.7 on 2023-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettingsdb',
            name='str',
            field=models.CharField(max_length=100),
        ),
    ]
