# Generated by Django 4.1.7 on 2023-04-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_adminsettingsdb_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettingsdb',
            name='int',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettingsdb',
            name='str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
