# Generated by Django 4.1.7 on 2023-04-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_adminsettingsdb_int_alter_adminsettingsdb_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettingsdb',
            name='int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
