# Generated by Django 4.1.7 on 2023-06-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
