# Generated by Django 4.1.7 on 2023-04-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userdb_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
