# Generated by Django 4.1.7 on 2023-04-07 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDB',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('hit', models.IntegerField(default=0)),
                ('recommend', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 1, 11, 741004))),
                ('updatedate', models.DateTimeField(default=datetime.datetime(2023, 4, 7, 13, 1, 11, 741012))),
            ],
        ),
    ]
