# Generated by Django 4.1.7 on 2023-06-15 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(default='일반', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CommunitycommentDB',
            fields=[
                ('comment_num', models.AutoField(primary_key=True, serialize=False)),
                ('post_num', models.IntegerField()),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=12)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityDB',
            fields=[
                ('post_num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('hit', models.IntegerField(default=0)),
                ('recommend', models.JSONField(default=list)),
                ('comment_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isRecommend', models.BooleanField(default=False)),
            ],
        ),
    ]
