# Generated by Django 4.1.7 on 2023-04-12 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitydb',
            old_name='num',
            new_name='post_num',
        ),
        migrations.AddField(
            model_name='communitydb',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitydb',
            name='id',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communitydb',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='communitydb',
            name='updatedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
