# Generated by Django 4.1.7 on 2023-04-12 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_rename_num_communitydb_post_num_communitydb_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitycommentDB',
            fields=[
                ('comment_num', models.AutoField(primary_key=True, serialize=False)),
                ('post_num', models.IntegerField()),
                ('id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=300)),
                ('comment_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='communitydb',
            old_name='createdate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='communitydb',
            old_name='updatedate',
            new_name='update_date',
        ),
        migrations.AddField(
            model_name='communitydb',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
