# Generated by Django 4.1.7 on 2023-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communitycommentdb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(default='일반', max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='communitycommentdb',
            name='comment_count',
        ),
    ]
