# Generated by Django 4.1.7 on 2023-04-18 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_communitycommentdb_id_alter_communitydb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycommentdb',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='communitycommentdb',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='communitydb',
            name='id',
            field=models.IntegerField(),
        ),
    ]
