# Generated by Django 4.1.7 on 2023-04-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_communitycommentdb_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydb',
            name='recommend',
            field=models.CharField(default=[], max_length=2000),
        ),
    ]
