# Generated by Django 4.1.7 on 2023-04-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_communitydb_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydb',
            name='recommend',
            field=models.JSONField(default=list),
        ),
    ]
