# Generated by Django 4.1.7 on 2023-04-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_communitydb_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydb',
            name='isRecommend',
            field=models.BooleanField(default=False),
        ),
    ]
