# Generated by Django 4.1.7 on 2023-04-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_communitydb_isrecommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycommentdb',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitycommentdb',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='communitydb',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='communitydb',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='communitydb',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='communitydb',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
