# Generated by Django 4.1.7 on 2023-06-15 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('knowBodyFat', models.BooleanField()),
                ('neck', models.FloatField(null=True)),
                ('waist', models.FloatField(null=True)),
                ('hip', models.FloatField(null=True)),
                ('bodyFat', models.IntegerField()),
                ('bmr', models.IntegerField()),
                ('activityLevel', models.FloatField()),
                ('totalEnergy', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('activity', models.JSONField()),
                ('change', models.IntegerField(null=True)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
