# Generated by Django 4.1.7 on 2023-06-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengedb',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='challengedb',
            name='hip',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='challengedb',
            name='neck',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='challengedb',
            name='waist',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='challengedb',
            name='weight',
            field=models.FloatField(),
        ),
    ]
